### ISSUE TITLE
AutoJump for <SELECT> input

### ISSUE THREAD

**Issue by dillahus** [josem/jquery.autojump#1]
Hi,
I have a drop-down list I would like to include in my autoskip.  I tried called your script using
$("input,select,textarea").autoJump();

but it did not work.  The select drop-down was completely skipped.

Shenda

**Comment by josem** [comment]
HI @dillahus! 

Sorry for the delay on this one, for some reason I didn't see the notification.

You are totally right, I forgot to include the select field and now it should be ok, I've just released a new version: https://github.com/josem/jquery.autojump/releases.

Please let me know if that helps at all, sorry for the troubles! :)
