### ISSUE TITLE
using your plugin from within a more complex that inputs exist within divs

### ISSUE THREAD

**Issue by vahidhedayati** [josem/jquery.autojump#2]
The problem was that this did not appear to work when the form input elements were put within divs. The solution seems to be to replace:

```

if (currentLength === maxLength - 1) {
                $(this).one("keyup", function() {
                    //$(this).nextAll("input,textarea,select").first().focus();
                                        //with this - but then obviously the original method does not work
                    $(this).parent().next('div').find("input,textarea,select").first().focus();
```

If you could think of a way of both working that would be awesome

**Comment by josem** [comment]
Hi @vahidhedayati! Thanks so much for opening the issue :)

I've released a new version with a fix for this, you need to call the plugin now with "form" instead of "input, select, textareas".

Please, let me know if this helped :)

Thanks again!
